# tensor 向量
---
tensor是Pytorch中代表所有数据的格式，数据都被表述为不同的tensor

### 创建tensor

In [67]:
import torch
torch.__version__

'2.2.0+cu121'

In [68]:
# scala
scala = torch.tensor(5)
scala

tensor(5)

In [69]:
scala.ndim

0

In [70]:
# 从tensor中取回值
scala.item()

5

In [71]:
# vector
raw_array = [0,2,4]
vec = torch.tensor([i*2 for i in raw_array])
vec

tensor([0, 4, 8])

In [72]:
vec.ndim

1

In [73]:
vec.shape

torch.Size([3])

In [74]:
matrix = torch.tensor([[0,1],
                      [1,0]])
matrix

tensor([[0, 1],
        [1, 0]])

In [75]:
matrix.ndim, matrix.shape

(2, torch.Size([2, 2]))

### 随机tensor
神经网络学习通常从一个随机的tensor开始，通过分析数据得到一个更好的tensor

In [76]:
#  创建随机的tensor
random_tensor = torch.rand(5,3)
random_tensor

tensor([[0.2745, 0.6584, 0.2775],
        [0.8573, 0.8993, 0.0390],
        [0.9268, 0.7388, 0.7179],
        [0.7058, 0.9156, 0.4340],
        [0.0772, 0.3565, 0.1479]])

In [77]:
# 例如，如果想创建一个表述图片的tensor，你可以用（长，高，色彩通道(rgb)）
random_tensor = torch.rand(size=(3, 224, 224))
random_tensor

tensor([[[0.5331, 0.4066, 0.2318,  ..., 0.1547, 0.5185, 0.2337],
         [0.9794, 0.7788, 0.7945,  ..., 0.0121, 0.2541, 0.0475],
         [0.7690, 0.8418, 0.5438,  ..., 0.0540, 0.7117, 0.0697],
         ...,
         [0.7690, 0.4457, 0.8744,  ..., 0.2655, 0.8964, 0.1610],
         [0.2855, 0.3935, 0.2935,  ..., 0.6797, 0.9579, 0.4980],
         [0.2928, 0.4907, 0.1513,  ..., 0.2940, 0.9641, 0.8343]],

        [[0.1836, 0.4004, 0.6376,  ..., 0.6506, 0.9169, 0.8209],
         [0.5375, 0.4618, 0.8188,  ..., 0.6726, 0.6767, 0.8444],
         [0.4847, 0.5233, 0.4279,  ..., 0.4169, 0.5045, 0.9183],
         ...,
         [0.1147, 0.7772, 0.0530,  ..., 0.4248, 0.5969, 0.3289],
         [0.9373, 0.3691, 0.6035,  ..., 0.5395, 0.5678, 0.7011],
         [0.3381, 0.8708, 0.5258,  ..., 0.8066, 0.3758, 0.9334]],

        [[0.4449, 0.3963, 0.0566,  ..., 0.0804, 0.7895, 0.2719],
         [0.8593, 0.0204, 0.0520,  ..., 0.4014, 0.8286, 0.5475],
         [0.4855, 0.8883, 0.2936,  ..., 0.3810, 0.7540, 0.

In [78]:
# 通过控制随机种子控制随机量
RAND_SEED = 123
torch.manual_seed(RAND_SEED)
rt1 = torch.rand(size=(3,4))
# 每次生成后种子都会被刷新，需要重新进行指定
torch.manual_seed(RAND_SEED)
rt2 = torch.rand(size=(3,4))
rt1, rt2

(tensor([[0.2961, 0.5166, 0.2517, 0.6886],
         [0.0740, 0.8665, 0.1366, 0.1025],
         [0.1841, 0.7264, 0.3153, 0.6871]]),
 tensor([[0.2961, 0.5166, 0.2517, 0.6886],
         [0.0740, 0.8665, 0.1366, 0.1025],
         [0.1841, 0.7264, 0.3153, 0.6871]]))

In [79]:
# 也可以创建全部为0或全部为1的tensor
zeros = torch.zeros(size=(3,4))
ones = torch.ones(size=(3,4))
# 两个tensor相乘
zeros, ones, zeros*ones

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]))

### 范围


In [80]:
zero_to_ten = torch.arange(start=1, end=11)
zero_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [81]:
# step
torch.arange(start=1, end=1000, step=5)

tensor([  1,   6,  11,  16,  21,  26,  31,  36,  41,  46,  51,  56,  61,  66,
         71,  76,  81,  86,  91,  96, 101, 106, 111, 116, 121, 126, 131, 136,
        141, 146, 151, 156, 161, 166, 171, 176, 181, 186, 191, 196, 201, 206,
        211, 216, 221, 226, 231, 236, 241, 246, 251, 256, 261, 266, 271, 276,
        281, 286, 291, 296, 301, 306, 311, 316, 321, 326, 331, 336, 341, 346,
        351, 356, 361, 366, 371, 376, 381, 386, 391, 396, 401, 406, 411, 416,
        421, 426, 431, 436, 441, 446, 451, 456, 461, 466, 471, 476, 481, 486,
        491, 496, 501, 506, 511, 516, 521, 526, 531, 536, 541, 546, 551, 556,
        561, 566, 571, 576, 581, 586, 591, 596, 601, 606, 611, 616, 621, 626,
        631, 636, 641, 646, 651, 656, 661, 666, 671, 676, 681, 686, 691, 696,
        701, 706, 711, 716, 721, 726, 731, 736, 741, 746, 751, 756, 761, 766,
        771, 776, 781, 786, 791, 796, 801, 806, 811, 816, 821, 826, 831, 836,
        841, 846, 851, 856, 861, 866, 871, 876, 881, 886, 891, 8

### 相似的tensor

In [82]:
orgin_tensor = torch.tensor([[1,2],
                             [1,3]])
torch.zeros_like(input=orgin_tensor)

tensor([[0, 0],
        [0, 0]])

In [83]:
torch.ones_like(input=orgin_tensor)

tensor([[1, 1],
        [1, 1]])

### tensor的数据类型

In [84]:
float_tensor = torch.arange(start=1,end=10,dtype=torch.float16,step=0.5)
float_tensor

tensor([1.0000, 1.5000, 2.0000, 2.5000, 3.0000, 3.5000, 4.0000, 4.5000, 5.0000,
        5.5000, 6.0000, 6.5000, 7.0000, 7.5000, 8.0000, 8.5000, 9.0000, 9.5000],
       dtype=torch.float16)

In [85]:
torch.arange(start=1,end=10,dtype=torch.int16)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int16)

In [86]:
# 类型转换
float_tensor.type(dtype=torch.int8)

tensor([1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 8, 8, 9, 9],
       dtype=torch.int8)