In [34]:
import torch
torch.__version__

'2.2.0+cu121'

### 相加

In [35]:
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

### 相乘

In [36]:
tensor * 10

tensor([10, 20, 30])

### 矩阵相乘

In [37]:
tensor_a = torch.tensor([[1,2,3]])
tensor_b = torch.tensor([
    [2],
    [3],
    [4]
])
tensor_a * tensor_b

tensor([[ 2,  4,  6],
        [ 3,  6,  9],
        [ 4,  8, 12]])

In [38]:
# 最大最小
tensor = torch.tensor([5,6,1,7,9])
tensor.min(), tensor.max()

(tensor(1), tensor(9))

In [39]:
# tensor 变形
tensor = torch.arange(1,11,1)
# tensor.view() 不会分配新的内存，只是改变了观察方式
tensor.reshape(1,1,10), tensor.view(1,1,10)

(tensor([[[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]]]),
 tensor([[[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]]]))

### tensor的堆叠

In [40]:
tensor = torch.tensor([1,2,3])
tensor = torch.stack([tensor, tensor+1, tensor])
tensor

tensor([[1, 2, 3],
        [2, 3, 4],
        [1, 2, 3]])

In [41]:
# dim参数作用
tensor = torch.tensor([1,2,3])
tensor = torch.stack([tensor, tensor+1, tensor], dim=1)
tensor

tensor([[1, 2, 1],
        [2, 3, 2],
        [3, 4, 3]])

In [42]:
tensor = torch.tensor([[1,2,3]])
tensor, tensor.squeeze()

(tensor([[1, 2, 3]]), tensor([1, 2, 3]))

In [43]:
tensor = torch.tensor([1,2,3])
tensor, tensor.unsqueeze(dim=0), tensor.unsqueeze(dim=1)

(tensor([1, 2, 3]),
 tensor([[1, 2, 3]]),
 tensor([[1],
         [2],
         [3]]))

### 从tensor中取出数据

In [44]:
tensor = torch.tensor([[1,2,3],
                       [4,5,6],
                       [7,8,9]])
# 用“ ：”代表这一层的所有数据
tensor[0], tensor[:,1], tensor[1, 2]

(tensor([1, 2, 3]), tensor([2, 5, 8]), tensor(6))