In [1]:
import torch
import numpy as np
torch.__version__

'2.2.0+cu121'

### tensor和numpy的互相转换

In [2]:
# tensor转换为numpy
tensor = torch.tensor([1,2,3])
array = tensor.numpy()
array, tensor

(array([1, 2, 3]), tensor([1, 2, 3]))

In [3]:
# numpy转化为tensor
array = np.arange(1,6)
tensor = torch.from_numpy(array)
array, tensor

(array([1, 2, 3, 4, 5]), tensor([1, 2, 3, 4, 5]))

In [4]:
# 相互转换时都分配了新内存，对原始数据的修改不影响新变量
array = np.arange(1,6)
tensor = torch.from_numpy(array)
array = array + 1
array, tensor

(array([2, 3, 4, 5, 6]), tensor([1, 2, 3, 4, 5]))

In [5]:
tensor = torch.tensor([1,2,3])
array = tensor.numpy()
tensor = tensor + 1
array, tensor

(array([1, 2, 3]), tensor([2, 3, 4]))